version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network            

  server1:
    build:
      context: ./server1
    container_name: server1
    depends_on:
      - rabbitmq
    ports:
      - "8001:8001"
    networks:
      - my_network      

  server2:
    build:
      context: ./server2
    container_name: server2
    volumes:
      - ./logs:/app/logs
    depends_on:
      - rabbitmq
    ports:
      - "8002:8002"
    networks:
      - my_network      

  server3:
    build:
      context: ./server3
    container_name: server3
    volumes:
      - ./logs:/app/logs
    depends_on:
      - rabbitmq
    ports:
      - "8003:8003"
    networks:
      - my_network    

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - my_network

networks:
  my_network:
    driver: bridge